#!/bin/bash

project_name="projectforge"

 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\$project_name-application -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"
 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\$project_name-business -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"
 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\$project_name-common -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"
 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\$project_name-excel -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"
 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\$project_name-integration-test -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"
 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\$project_name-jax-rs -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"
 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\$project_name-launcher -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"
 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\$project_name-model -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"
 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\$project_name-wicket -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"
 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\plugins -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"
 ./..\SourceMeter-8.1.0-x64-linux\Java\SourceMeterJava -projectName=$project_name -projectBaseDir=..\..\Projects\$project_name\tools -resultsDir=..\Results -runFB=false -runPMD=false -runFaultHunter=false -runAndroidHunter=false -runVulnerabilityHunter=false -csvSeparator=";"


./..\findbugs-3.0.1\bin\findbugs -textui -maxRank 14 -progress -xml -output ..\Results\$project_name\FindBugs\$project_name.xml ..\..\Projects\$project_name\